# Generated by Django 4.1 on 2022-09-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0002_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="website",
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateField(),
        ),
    ]
