# Generated by Django 4.1 on 2022-09-22 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0003_event_website_alter_event_end_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="location",
            new_name="event_location",
        ),
    ]
