# Generated by Django 4.1 on 2022-09-24 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0004_rename_location_event_event_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="website",
        ),
    ]
