# Generated by Django 4.1 on 2022-10-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0005_remove_event_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateField(max_length=8, null=True),
        ),
    ]
