# Generated by Django 4.1 on 2022-10-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0005_remove_event_website"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="event_location",
            new_name="address",
        ),
    ]
